### ISSUE TITLE
Issue with viewing stats

### ISSUE THREAD

**Issue by filasik** [AsyncDevTeam/mcMMO-Stats-Panel#11]
Hello, I'm getting error message:

An error occured : Error loading top leaderboard
If you don't understand it, please contact the developers.

Web:
https://hcraft.cz/mcmmo/index.php

Could you please help me with that? Thank you.

**Comment by NicolasVaillant** [comment]
Hello @filasik, 
It seems there has been a failure in connecting to your database. 
We have already fixed this type of problem for some users. It is an issue on the user's side. 

Try to run ```/resources/php/scripts/get_top_leaderboard.php```, you'll see that the access to your db is denied. 

Therefore, please take a look at these elements:
-  Ensure that your config.php file has the correct configuration
-  Ensure that the official mcMMO plugin has database storage enabled
-  Check your PHP version (mcMMO Dashboard requires PHP 8)

Let us know when your issue is fixed!
Thank you for using mcMMO Dashboard!
BR

**Comment by filasik** [comment]
Project is great.

I just verified if I have remote access to DB enabled and it is OK.
Storage is enabled,  I checked that there are 2 rows in the mcmmo tables.

Does it really matter if I use PHP 7.4 instead of PHP 8?

**Comment by NicolasVaillant** [comment]
Unfortunately, yes. This is one of the requirements of the project. We must use at least one function running on PHP 8.X. 

I assigned @Royalphax to the issue; he is the backend guy. He can't do anything more, but maybe he can explain the details to you. 

For the moment, upgrade your server! 🆙

**Comment by filasik** [comment]
Thank you for information, I see that you're using `str_starts_with()` function from newer PHP. Im now upgrading the server and let you know if it works in the edited answer.

Cheers 💚


Edit: everything fine https://skerik.online/mcmmo/

Keep up the great work!

**Comment by NicolasVaillant** [comment]
Perfect! I'm closing this issue. 

Glad to have you on board. Don't hesitate to join our [Discord channel](https://discord.gg/JNugRFWBA) to be part of our growing community! I would like to display your dashboard on our [landing page](mcmmo.nicolasvaillant.net), are you okay with it?
