### ISSUE TITLE
secure.php return 'Request not authorized'

### ISSUE THREAD

**Issue by NicolasVaillant** [AsyncDevTeam/mcMMO-Stats-Panel#2]

**Comment by Royalphax** [comment]
***How to verify the origin of the requests from the php scripts in order to avoid malicious attacks ?***

Before, I was thinking of an easy way by just comparing the request IP address with the server IP address. This was not working at all since the website was hosted on another machine. The result was the file `secure.php` always returning `Request not authorized`.

That's why I implemented it in the CSRF Token way. The idea behind it is to generate a CSRF Token (random UUID) at each start of a user session (server side). This token is then passed in the html to be get by the javascript to request to php files. On the side of the php files the CSRF token is verified. If it is invalid, it will return "Access denied"
